<?php

/**
 * @file
 * demo.module
 */

/**
 * Implement hook_block_info().
 */
function demo_block_info() {
    $blocks['demo'] = array(
        'info' => t('Demo Block'),
    );
    return $blocks;
}

/**
 * Implement hook_block_view().
 */
function demo_block_view($delta = '') {
    $block = array();

    switch ($delta) {
        case 'demo':
            $block['subject'] = t('Demo Custom Block');
            $block['content'] = "<strong>Hello World!</strong>";
            break;
    }
    return $block;
}
/*
 * Implement hook_permissions().
 */
function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer demo module'),
      'description' => t('Perform administration tasks for the Demo module'),
    )
  );
 }

/*
 * Implement hook_node_view().
*/
function demo_node_view($node, $view_mode, $langcode) {

}

/*
 * Implement hook_menu().
 */
function demo_menu() {
  $items = array();

  $items['demo'] = array(
    'title' => 'Drupal 7 custom module demo',
    'page callback' => 'demo_basic',
    'access arguments' => array('access content'),
  );

  $items['demo/%'] = array(
    'title' => 'Drupal 7 custom module demo wildcard callback',
    'page callback' => 'demo_basic_extra',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'demo_basic.extra.inc',
  );

  $items['user/%/demo'] = array(
    'title' => 'Demo',
    'description' => 'Demo of menu tab',
    'page callback' => 'demo_user_tab',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'file' => 'demo.user.inc',
    'type' => MENU_LOCAL_TASK,
   );

  return $items;
}

function demo_basic() {
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Drupal 7 demo page markup</p>',
  );
  return $content;
}
