<?php

/*
 * Implement hook_permissions().
 */
function demo_permission() {
  return array(
    'administer demo module' => array(
      'title' => t('Administer demo module'),
      'description' => t('Perform administration tasks for the Demo module'),
    )
  );
 }

/*
 * Implement hook_node_view().
*/
function demo_node_view($node, $view_mode, $langcode) {

  krumo($node);
}

/*
 * Implement hook_menu().
 */
function demo_menu() {
  $items = array();

  $items['demo'] = array(
    'title' => 'Drupal 7 custom module demo',
    'page callback' => 'demo_basic',
    'access arguments' => array('access content'),
  );

  return $items;
}

function demo_basic() {
  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Drupal 7 demo page markup</p>',
  );
  return $content;
}
